name: Security Testing with OWASP ZAP
on:
  push:
    branches:
      - main
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://localhost -g gen.conf -r zap_report.html
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-report
          path: zap_report.html

  orchestron-report:
    runs-on: ubuntu-latest
    needs: zap-scan
    steps:
      - name: Upload to Orchestron
        run: |
          curl -H "Secret-Key: ${{ secrets.ORCHESTRON_SECRET }}" -H "Access-Key: ${{ secrets.ORCHESTRON_ACCESS }}" -F file=@zap_report.html http://localhost/api/webhooks/post/...
